# Generated by scripts/release.mjs from verified release assets.
class Reddit < Formula
  desc "Archive Reddit listings as JSON and media with an offline viewer"
  homepage "https://github.com/reddit-rs/reddit"
  version "0.5.4"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    depends_on macos: :sonoma
    on_arm do
      url "https://github.com/reddit-rs/reddit/releases/download/v0.5.4/reddit-v0.5.4-aarch64-apple-darwin.tar.gz"
      sha256 "b7600813260345667e4afb1a4bb838122a6a57e6edc687c89031f97eb327667d"
    end
    on_intel do
      url "https://github.com/reddit-rs/reddit/releases/download/v0.5.4/reddit-v0.5.4-x86_64-apple-darwin.tar.gz"
      sha256 "003488838327fbb33273937a47f54e1c38c05410bb601526c8426f198af3e4fa"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/reddit-rs/reddit/releases/download/v0.5.4/reddit-v0.5.4-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "b78c8e75d52b2267e4d4508fa6f78982df45c6b6df5de38f21ad6d2a6c3f5c3c"
    end
    on_intel do
      url "https://github.com/reddit-rs/reddit/releases/download/v0.5.4/reddit-v0.5.4-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "b16152bf879355af22749bcc22236e9d4fdcae39d5713840e9881d49258d2283"
    end
  end

  def install
    bin.install "reddit"
  end

  test do
    assert_match "reddit #{version}", shell_output("#{bin}/reddit --version")
  end
end
