# Generated by scripts/release.mjs from verified release assets.
class Reddit < Formula
  desc "Archive Reddit listings as JSON and media with an offline viewer"
  homepage "https://github.com/reddit-rs/reddit"
  version "0.5.1"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    depends_on macos: :sonoma
    on_arm do
      url "https://github.com/reddit-rs/reddit/releases/download/v0.5.1/reddit-v0.5.1-aarch64-apple-darwin.tar.gz"
      sha256 "39945cefca58269f181d56fcbdf296dc42ddb430558419b14ae2de5ba048e791"
    end
    on_intel do
      url "https://github.com/reddit-rs/reddit/releases/download/v0.5.1/reddit-v0.5.1-x86_64-apple-darwin.tar.gz"
      sha256 "bb700b1f92f1103e72ab09f52c0538dca8c66075ed6aa1c6da63922954af7af4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/reddit-rs/reddit/releases/download/v0.5.1/reddit-v0.5.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "a13a0617c5130fc8b7d426aa12ae70fad623e43a4549b50c5bb521c937885385"
    end
    on_intel do
      url "https://github.com/reddit-rs/reddit/releases/download/v0.5.1/reddit-v0.5.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "03f1e28f4f6a4d74f801995669a1cb8c9cc594ecb5ff551af1939eae4f941b89"
    end
  end

  def install
    bin.install "reddit"
  end

  test do
    assert_match "reddit #{version}", shell_output("#{bin}/reddit --version")
  end
end
